---
title: Python 2.7.x使用pip报错
date: 2023-09-29 21:43:39
updated: 2023-09-29 21:43:41
tags:
  - Bugs
categories: Bugs解决
keywords:
  - Bugs解决
description: 由于某些作业的需求，我不得不使用 python 2.7.x，但是在使用pip安装软件包的过程中出现了ASCII报错。
top_img:
comments:
cover:
toc:
toc_number:
toc_style_simple:
copyright:
copyright_author:
copyright_author_href:
copyright_url:
copyright_info:
mathjax:
katex:
aplayer:
highlight_shrink:
aside:
abcjs:
---

#### 问题描述

由于某些作业的需求，我不得不使用 python 2.7.x（甚至是跑人工智能，甚至还在用python2，真是吃不消了），用 conda 创建完 python 2.7.x 的环境后准备用 pip 安装软件包，然后就开始疯狂报错orz

报错内容如下：

```shell
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting Pillow==3.4.2
ERROR: Exception:
Traceback (most recent call last):
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\cli\base_command.py", line 153, in _main
    status = self.run(options, args)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\commands\install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\operations\prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\download.py", line 316, in unpack_http_url
    progress_bar)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\download.py", line 549, in _download_http_url
    file_path = os.path.join(temp_dir, filename)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 7: ordinal not in range(128)
(ai1) PS D:\JetBrains\JetbrainProjects\PyCharmProjects\AI\lab1> pip install pillow==3.4.2
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pillow==3.4.2
ERROR: Exception:
Traceback (most recent call last):
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\cli\base_command.py", line 153, in _main
    status = self.run(options, args)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\commands\install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\operations\prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\download.py", line 316, in unpack_http_url
    progress_bar)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\download.py", line 549, in _download_http_url
    file_path = os.path.join(temp_dir, filename)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 7: ordinal not in range(128)
(ai1) PS D:\JetBrains\JetbrainProjects\PyCharmProjects\AI\lab1> pip install scipy==0.18.1
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting scipy==0.18.1
ERROR: Exception:
Traceback (most recent call last):
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\cli\base_command.py", line 153, in _main
    status = self.run(options, args)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\commands\install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\operations\prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\download.py", line 316, in unpack_http_url
    progress_bar)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\site-packages\pip\_internal\download.py", line 549, in _download_http_url
    file_path = os.path.join(temp_dir, filename)
  File "D:\Code_about\Anaconda3\envs\ai1\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 7: ordinal not in range(128)
```

#### 解决方案

前面的几行都
